[package]
name = "rpg_modifiers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.17.0"
ruscii = "0.3"
rand = "0.8.4"